name: ${COMPOSE_PROJECT_NAME}
services:
  mysql:
    container_name: ${DB_CONTAINER_NAME}
    image: mysql:8.0
    ports:
      - 127.0.0.1:${DATABASE_PORT:-3310}:3306
    volumes:
            - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    command:
      [
          "--character-set-server=utf8mb4",
          "--collation-server=utf8mb4_unicode_ci",
          "--default-authentication-plugin=mysql_native_password",
      ]
    healthcheck:
      test: "mysqladmin ping -h 127.0.0.1 -u root"
      timeout: 5s
      interval: 5s
      retries: 10
volumes:
  mysql-data: